Update workflow

diff --git a/.github/workflows/stag-release.yaml b/.github/workflows/stag-release.yaml
--- a/.github/workflows/stag-release.yaml
+++ b/.github/workflows/stag-release.yaml
@@ -26,16 +26,6 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Copy files via SSH on Test Server
-        uses: appleboy/scp-action@v0.1.7
-        with:
-          host: ${{ secrets.TEST_HOST_1 }}
-          username: ${{ secrets.TEST_HOST_1_USERNAME}}
-          port: 22
-          password: ${{ secrets.TEST_HOST_1_PASSWORD}}
-          source: "*"
-          target: ${{ secrets.TEST_HOST_1_APPDIR }}/DbMigrations
-
       - name: Run migrations on Test Server
         uses: appleboy/ssh-action@v0.1.5
         with:
@@ -45,8 +35,10 @@ jobs:
           port: 22
           script: |
             cd ${{ secrets.TEST_HOST_1_APPDIR }}/DbMigrations/DatabaseMigrations
-            
-            dotnet build
+
+            git checkout -f develop
+            git reset --hard
+            git pull || { echo "Git pull failed"; exit 1; }
 
             dbType=${{ github.event.inputs.dbType }}
             migrate=${{ github.event.inputs.migrate }}
@@ -61,8 +53,16 @@ jobs:
             fi
 
             if [ -z "$targetVersion" ]; then
-              dotnet run dbType=$dbType migrate=$migrate
+              runCommand="dotnet run dbType=$dbType migrate=$migrate"
             else
-              dotnet run dbType=$dbType migrate=$migrate targetVersion=$targetVersion
+              runCommand="dotnet run dbType=$dbType migrate=$migrate targetVersion=$targetVersion"
             fi
+
+            # Log the command
+            echo "Running command: $runCommand"
+
+            # Run the command
+            dotnet clean
+            dotnet build || { echo "Build failed"; exit 1; }
+            $runCommand || { echo "Migration command failed"; exit 1; }
 
